### PR TITLE
Save raw params for scrolling

### PR DESCRIPTION
**Pull request by warewolf**
Not sure if the search_params value in the Search role was intended for this use, but I ran into this bug today and decided to fix it.  Thanks for putting this code up on github :)

### CODE REVIEW

**Comment by clintongormley** [comment]
Hi @warewolf 

What bug do you think there is?  You shouldn't be passing the original search_params to the scroll request, unless I've missed something?

**Comment by warewolf** [comment]
If I'm talking to an elasticsearch instance that is behind a proxy (atleast, I think that's how the one I'm poking at works, I'm only guessing here) that uses authentication in the request URL, like "session_key" for example, that gets lost when I scroll through a result set.  My patch passes it through for scrolling.

ex:
``` perl
my $ES = Search::Elasticsearch->new( # {{{
  client   => '0_90::Direct',
  cxn => 'LWP',
  nodes    => [ "https://search.example.com/protected/es/", ],
  cxn_pool => 'Static::NoPing',
); # }}}

  my $scroller = Search::Elasticsearch::Scroll->new(
    es     => $ES,
    index  => "machines",
    size   => 20,
    fields => $opts->{fields}, 
    params => { session_key => $ENV{SESSION_KEY}, },
    body => {
      "query" => {
        "filtered" => {
          "query"  => { "match_all" => {} },
          "filter" => {
            # ... filter expr  ...
           }
         }
       }
     }
  ); 
```
During this loop, after the first 20 results have been iterated through, the refill_buffer method calls scroll_request with the raw URI params missing, which then causes the server I'm scrolling to say "Invalid request".

``` perl
  while ( my $result = $scroller->next() ) { # {{{
    # ... print contents of $result ...
  } 
```

I'm not an administrator of the ES instance I'm talking to, just a consumer.  I suspect this is a method they decided on to protect this ES instance from abuse by requiring an authentication token.

**Comment by warewolf** [comment]
Oh, I see what you're referring to with "passing the original search params".. I was unsure about using the search_params variable, and I see now that it's being used for something else.  I did a cursory grep and didn't think it was being used.

I hope my above explanation of the situation (and my method of fixing it) is descriptive enough - I'd like to see this functionality upstream, but if using search_params is wrong, then feel free to reject -> modify -> merge the code or something.

**Comment by clintongormley** [comment]
OK I understand what you're doing now.  I think this should be solved differently.  At the moment you can specify `default_headers` that will be added to every request.  I think we should add  `default_params` too, then you can just specify your session key when you create the client, and never have to think about it again after that.

**Comment by warewolf** [comment]
Awesome!  Thanks.

**Pull request closed without merging**
