### PR TITLE
Fix retry_on_conflict in bulk api

### PR DESCRIPTION
**Pull request by AnaTofuZ**
The following warnings occurred when using retry_on_conflict with bulk update api

```
[DEPRECATION] Unknown field [retry_on_conflict] used in UpdateRequest which has no value and will not be accepted in future
```

Here is what the documentation says

> When using the update action, retry_on_conflict can be used as a field in the action itself (not in the extra payload line), to specify how many times an update should be retried in the case of a version conflict.

https://www.elastic.co/guide/en/elasticsearch/reference/6.8/docs-bulk.html

However, the JSON generated by the current Client is different, looking something like this

```json
{"update":{"_id":"1234567"}}
{"retry_on_conflict":3,"doc":{"baz":1}}
```

This is the way it should be, and I've modified it so that it can be.
```json
{"update":{"_id":"1234567","retry_on_conflict":3}}
{"doc":{"baz":1}}
```

I have confirmed that it seems to be working with ES6.

### CODE REVIEW

**Comment by AnaTofuZ** [comment]
Oops, I got conflicted with the recent commit. I will try to correct it.

**Comment by AnaTofuZ** [comment]
Oops... To make matters worse, we wanted to use this fix in the 6 client, but Perl Client just cut off support for the 6 series.
Is it possible to apply this bug fix to the Series 6 client as well?

**Comment by AnaTofuZ** [comment]
@ezimuel 
I apologize for the inconvenience, but could you please review this pull request? If possible, I would also like to incorporate these changes into the currently uploaded Client6 on CPAN.

**Comment by ezimuel** [comment]
I'm sorry but  we are not supporting anymore 6.x version. We only support 7.x and 8.x.

**Pull request closed without merging**
