### PR TITLE
Fix typo in docs

### PR DESCRIPTION
**Pull request by jasonjayr**
Single character typo fix targer -> target

### CODE REVIEW

**Comment by clintongormley** [comment]
Hi @jasonjayr 

Sorry for the late reply and thanks for the fix.  Could I ask you to sign the CLA please, so that I can merge this in? http://www.elastic.co/contributor-agreement/

thanks

**Comment by clintongormley** [comment]
CLA not signed. Treating as bug report.

**Comment by jasonjayr** [comment]
FYI -- I totally missed the request for the CLA.  but the CLA is using Adobe's document cloud which is giving me trouble in chromium's default configuration -- is there another way I can sign?

**Comment by jasonjayr** [comment]
Actually -- nevermind, I figured out how to break the e-sign form out of the frame so I could complete it.  Let me know if you need anything else ...

**Comment by clintongormley** [comment]
thanks @jasonjayr  - i've already fixed the issue, but at least the CLA is signed for any future PRs :)

**Pull request closed without merging**
