### PR TITLE
Add support for retry_on_conflict parameter in bulk update

### PR DESCRIPTION
**Pull request by ikorchynskyi**

### CODE REVIEW

**Comment by karmi** [comment]
Hi @ikorchynskyi, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/elastic/elasticsearch-perl/pull/150.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by ikorchynskyi** [comment]
Hi @karmi, I signed CLA with the same email address I use for Github profile

**Comment by clintongormley** [comment]
Hi @ikorchynskyi 

Thanks for the PR.  You signed with your gmail address, but the commits use your port.... address.

**Comment by clintongormley** [comment]
Any chance you can add some tests to this to ensure that it is working?

**Comment by ikorchynskyi** [comment]
Added tests for 2.0, 5.0, 6.0, removed changes for 0.9, 1.0 APIs, as I actually can't check that versions.

**Comment by clintongormley** [comment]
That's great @ikorchynskyi - thanks so much.

**Pull request merged**
