### PR TITLE
Search::Elasticsearch errors should be JSON-compatible

### PR DESCRIPTION
**Pull request by sewi-cpan**
Converting a Search::Elasticsearch error to JSON (within some structure) fails like this:
`encountered object '[Request] ** [http://localhost:9200]-[400] SearchPhaseExecutionException[Failed to execute phase [query], all shards failed; [...] 'method' => 'GET'},'status_code' => 400}
', but neither allow_blessed nor convert_blessed settings are enabled at /usr/share/perl5/JSON.pm line 154.`

This is bad, because the Search::Elasticsearch::Error object stringifies in text context, also in the error message. Developers don't see that the error is an object and wonder why it can't be transported.

Avoiding these crashes is easy, because the JSON module offers a solution for objects to stringify themself. This pull request introduces JSON support for the error module.

PS: I tried to put the test into the best location, please move it if you want to have it at a different place.

### CODE REVIEW

**Comment by clintongormley** [comment]
Hi @sewi-cpan 

Thanks for the PR.  Please could you use JSON::PP instead of JSON, as there is no need to add an extra dependency.

thanks

**Comment by sewi-cpan** [comment]
The JSON module is optional and used for testing only. The test just skips if JSON is not available. It should not be a dependency of Search::Elasticsearch.
The documentation refers to JSON, because JSON::PP and JSON::XS are selected automatically if they're available and JSON is their common wrapper.

**Comment by clintongormley** [comment]
I realise that, but JSON::PP is a core module and is already required, so then we can always run this test.

**Comment by sewi-cpan** [comment]
Changed JSON to JSON::PP.

**Pull request closed without merging**
