### PR TITLE
Prep for 6.8 release

### PR DESCRIPTION
**Pull request by ezimuel**
This PR contains the API endpoints update for `Elasticsearch 6.8.7`. Moreover, it includes the unit test and YAML test for OSS and XPack.

This PR fixes also #179 exposing an `xpack` object. The XPack endpoints have been moved into the Direct client, there's no need anymore to specify XPack as plugin.

### CODE REVIEW

**Comment by sewi-cpan** [comment]
https://github.com/elastic/elasticsearch-perl/pull/178/commits/f35efcbef6f2eaeb3dcc0eb5342cb3a777a2a59b#diff-87ca88ecdb2370e98cca19dade0beee4 looks like you left over some debugging stuff.

The commit includes a tidy of many files which hides the actual logic changes. Tidy is nice and every publich source should be tidy, but don't try to backdoor-introduce it to a project.

**Comment by ezimuel** [comment]
@sewi-cpan thanks for reporting. I'm still working on this PR and I'll remove the data dump and other includes.

**Comment by sewi-cpan** [comment]
> @sewi-cpan thanks for reporting. I'm still working on this PR and I'll remove the data dump and other includes.

Sorry, didn't recognize that you're maintainer :)
Some people tend to issue PRs on projects with minimal changes but huge formatting change.

**Comment by ezimuel** [comment]
@sewi-cpan don't worry. I'm glad that I have some code review. Thanks to you!

**Pull request merged**
